DATA_DIR = "./data"
ACCELERATOR = "gpu"
NUM_WORKERS = 1
FAST_DEV_RUN = False
OVERFIT_BATCHES = 1

EVAL_OOD = False
EVAL_SHIFT = False
VAL_SPLIT = 0.2

BATCH_SIZE = 128
AUTO_AUGMENT = "rand-m9-n2-mstd1"

NUM_CLASSES = 100
IN_CHANNELS = 3
STYLE = "cifar"
DROPOUT_RATE = 0.3
LR = 0.1
MOMENTUM = 0.9
WEIGHT_DECAY = 5e-4
NESTEROV = True

MILESTONES = [60, 120, 160]
GAMMA = 0.2

NUM_ESTIMATORS = 5

PRECISION = "16-mixed"
MAX_EPOCHS = 200
